# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 880)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1250, 880))
        MainWindow.setMaximumSize(QtCore.QSize(1250, 880))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/warf_parser_mini_imresizer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: #1e263e;\n"
"color: white;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.marketTable = QtWidgets.QTableWidget(self.centralwidget)
        self.marketTable.setGeometry(QtCore.QRect(4, 175, 1245, 611))
        self.marketTable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.marketTable.setToolTip("")
        self.marketTable.setStyleSheet("QHeaderView::section {\n"
"    background-color: #2b2b2b; /*шапка таблицы*/\n"
"    color: #ffffff;\n"
"    padding: 6px;\n"
"    border: 1px solid #444;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QHeaderView::section:hover {\n"
"    background-color: #3a3a3a; /*подсветка при наведении*/\n"
"}\n"
"\n"
"QTableWidget#marketTable {\n"
"    alternate-background-color: #18282f; \n"
"    background-color: #22323a;\n"
"    color: #efecec;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #2b2b2b; /* совпадает с фоном заголовков */\n"
"    border: 1px solid #444;    /* если нужен контур */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableWidget::item:selected:!active {\n"
"    background-color: #418fa5;\n"
"    color: #18252a;\n"
"}\n"
"\n"
"QToolTip {\n"
"    background-color: efecec; \n"
"    color: #2b2b2b;\n"
"    padding: 5px;\n"
"}")
        self.marketTable.setAlternatingRowColors(True)
        self.marketTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.marketTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.marketTable.setWordWrap(True)
        self.marketTable.setRowCount(0)
        self.marketTable.setColumnCount(8)
        self.marketTable.setObjectName("marketTable")
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.marketTable.setHorizontalHeaderItem(7, item)
        self.marketTable.horizontalHeader().setCascadingSectionResizes(True)
        self.marketTable.horizontalHeader().setDefaultSectionSize(135)
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(445, 815, 171, 28))
        self.add_btn.setStyleSheet("color: #18252a;\n"
"background-color: #418fa5;\n"
"font-weight: bold;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/assignment_add_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_btn.setIcon(icon1)
        self.add_btn.setObjectName("add_btn")
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn.setGeometry(QtCore.QRect(675, 815, 171, 28))
        self.delete_btn.setStyleSheet("color: #18252a;\n"
"background-color: #418fa5;\n"
"font-weight: bold;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/delete_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_btn.setIcon(icon2)
        self.delete_btn.setObjectName("delete_btn")
        self.buy_btn = QtWidgets.QPushButton(self.centralwidget)
        self.buy_btn.setGeometry(QtCore.QRect(1130, 225, 111, 28))
        self.buy_btn.setStyleSheet("QPushButton {\n"
"color: #418fa5;\n"
"border: 1px solid #418fa5;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #51cdd5;\n"
"    color: #171e21;\n"
"}\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/markdown_paste_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buy_btn.setIcon(icon3)
        self.buy_btn.setObjectName("buy_btn")
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn.setGeometry(QtCore.QRect(1130, 260, 111, 28))
        self.search_btn.setStyleSheet("QPushButton {\n"
"color: #418fa5;\n"
"border: 1px solid #418fa5;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #51cdd5;\n"
"    color: #171e21;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/search_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn.setIcon(icon4)
        self.search_btn.setObjectName("search_btn")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(160, 0, 801, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 45, 0, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 5, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("color: #efecec;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("color: #efecec;\n"
"font-weight: bold;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("color: #efecec;\n"
"font-weight: bold;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("color: #efecec;\n"
"font-weight: bold;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("color: #efecec;\n"
"font-weight: bold;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.market_logo_label = QtWidgets.QLabel(self.centralwidget)
        self.market_logo_label.setGeometry(QtCore.QRect(965, 60, 270, 71))
        self.market_logo_label.setOpenExternalLinks(True)
        self.market_logo_label.setObjectName("market_logo_label")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setEnabled(True)
        self.logo_label.setGeometry(QtCore.QRect(4, 52, 151, 110))
        self.logo_label.setOpenExternalLinks(True)
        self.logo_label.setObjectName("logo_label")
        self.settings_btn = QtWidgets.QPushButton(self.centralwidget)
        self.settings_btn.setGeometry(QtCore.QRect(4, 0, 101, 35))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/settings_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_btn.setIcon(icon5)
        self.settings_btn.setObjectName("settings_btn")
        self.lbl_name = QtWidgets.QLabel(self.centralwidget)
        self.lbl_name.setGeometry(QtCore.QRect(161, 0, 55, 35))
        self.lbl_name.setStyleSheet("color: #efecec;\n"
"font-weight: bold;")
        self.lbl_name.setObjectName("lbl_name")
        self.lbl_current_name = QtWidgets.QLabel(self.centralwidget)
        self.lbl_current_name.setGeometry(QtCore.QRect(222, 0, 131, 35))
        self.lbl_current_name.setStyleSheet("color: #efecec;\n"
"font-weight: bold;")
        self.lbl_current_name.setText("")
        self.lbl_current_name.setObjectName("lbl_current_name")
        self.lbl_platform = QtWidgets.QLabel(self.centralwidget)
        self.lbl_platform.setGeometry(QtCore.QRect(420, 0, 91, 35))
        self.lbl_platform.setStyleSheet("color: #efecec;\n"
"font-weight: bold;")
        self.lbl_platform.setObjectName("lbl_platform")
        self.lbl_current_platform = QtWidgets.QLabel(self.centralwidget)
        self.lbl_current_platform.setGeometry(QtCore.QRect(520, 0, 101, 35))
        self.lbl_current_platform.setStyleSheet("color: #efecec;\n"
"font-weight: bold;")
        self.lbl_current_platform.setText("")
        self.lbl_current_platform.setObjectName("lbl_current_platform")
        self.lbl_crossplat = QtWidgets.QLabel(self.centralwidget)
        self.lbl_crossplat.setGeometry(QtCore.QRect(710, 0, 171, 35))
        self.lbl_crossplat.setStyleSheet("color: #efecec;\n"
"font-weight: bold;")
        self.lbl_crossplat.setObjectName("lbl_crossplat")
        self.lbl_current_crossplat = QtWidgets.QLabel(self.centralwidget)
        self.lbl_current_crossplat.setGeometry(QtCore.QRect(887, 0, 71, 35))
        self.lbl_current_crossplat.setStyleSheet("color: #efecec;\n"
"font-weight: bold;")
        self.lbl_current_crossplat.setText("")
        self.lbl_current_crossplat.setObjectName("lbl_current_crossplat")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionactionSettings = QtWidgets.QAction(MainWindow)
        self.actionactionSettings.setObjectName("actionactionSettings")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PrimeParser"))
        item = self.marketTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Иконка"))
        item = self.marketTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Имя игрока"))
        item = self.marketTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Предмет"))
        item.setToolTip(_translate("MainWindow", "предмет с маркета"))
        item = self.marketTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Тип операции"))
        item.setToolTip(_translate("MainWindow", "покупка/продажа"))
        item = self.marketTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Количество"))
        item.setToolTip(_translate("MainWindow", "кол-во предметов"))
        item = self.marketTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Текущая цена"))
        item = self.marketTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Желаемая цена"))
        item.setToolTip(_translate("MainWindow", "ожидаемая цена"))
        item = self.marketTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "График цен"))
        self.add_btn.setText(_translate("MainWindow", "Добавить запись"))
        self.delete_btn.setText(_translate("MainWindow", "Удалить запись"))
        self.buy_btn.setText(_translate("MainWindow", "Купить"))
        self.search_btn.setText(_translate("MainWindow", "Поиск"))
        self.label.setText(_translate("MainWindow", "Инстукция к применению: "))
        self.label_2.setText(_translate("MainWindow", "1.  Выберите желаемый предмет на сайте Warframe.market."))
        self.label_3.setText(_translate("MainWindow", "2.  Заполните необходимые пункты, такие как \"Предмет\", \"Тип операции\", \"Количество\", \"Желаемая цена\"."))
        self.label_4.setText(_translate("MainWindow", "3.  Нажмите на кнопку \"Поиск\" справа от записи."))
        self.label_5.setText(_translate("MainWindow", "4.  Ожидайте по регулярно обновляемым данным, пока цена не достигнет указанного вами значения."))
        self.market_logo_label.setText(_translate("MainWindow", "<a href=\"https://warframe.market/\">\n"
"    <img src=\":/icons/wf_market_logo.png\">\n"
"</a>"))
        self.logo_label.setText(_translate("MainWindow", "<a href=\"https://github.com/Tenebrea/warframe-market-parser.git\">"
    "<img src=\":/icons/warf_parser_ic_big_imresizer.png\"/>"
    "</a>"))
        self.settings_btn.setText(_translate("MainWindow", "Настройки"))
        self.lbl_name.setText(_translate("MainWindow", "Ник:"))
        self.lbl_platform.setText(_translate("MainWindow", "Платформа:"))
        self.lbl_crossplat.setText(_translate("MainWindow", "Кроссплатформенность:"))
        self.actionactionSettings.setText(_translate("MainWindow", "actionSettings"))
import res_icon_rc
